server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.130.7.116:3306/system?
    username: root
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    aggressive-lazy-loading: true
  mapper-locations: classpath*:com/gdy/thieseback/mapper/*.xml
  type-aliases-package: com.gdy.thieseback.entity
